unique_ids:
  forms:
    Forms._FormTemplate: CR555ETJYVC7OP4KRQZXPBG6WJOFRZ33
  modules:
    Forms.Editor_Publish: JHL4YIMINUWDZEXRAFJ767JFDTRBGJXH
    Index: BLGAWSOBHTMN7ULTMMSJB347KCDBGAFZ
    Forms.Author_Stats: UEWT6U25NYJGEQXJ56ILSNVFD2IHBSU3
    Index.App: CI6THZVGTL4BDFHIOLWXA5ZKBEOOQVOV
    Forms.Reader_Charts: VLSSXS25OQKWJS6A2PCAVTXUOKKSR45O
    Forms.Reader_Bookmarks: KDK6I6PZMEMQFNRKF4MN66GFQCOASVBP
    Forms._Welcome: VC5L7UHUKZP5H7GLWQ2GYGGDX6WUMWIP
    Index.Device: G5H2CSQW7N2DWVGH2H7NTYRQLTFDOAPU
    Navigation.NavigationBar: 2VMZNWBGM5EXM3ABSMBCAHJULBYF7DZ6
    Navigation: 4REX5LJ6FFN6S6XJZFW5NV5KZATKOFO3
    Database.ChartsDB: OQXMDFVWRIYXNAMUIEZUZNMPKEUAYQJE
    Forms.Work_Cover: QKQEGFVDP3BMSAY6GM5CBVXB7VVTIJTH
    Forms.Settings_User.ZodParse: TXEWPWHTGESAZ2F7V5NM5AX6OG7ABADP
    Database.AwesomeDB: 3N4QVH6DW6OCUDZG5B2M67T4GLVW6ABE
    Forms.Author_Profile: TK4ACO5DVWOAX5OAYHLPR7VLR6H3FEKH
    Forms.Editor_Cover: J5HX3NEBVP4AUJLJNLIRSFAD7MQLBAW3
    Forms.Settings_User.Login: E6N6MYGAN5N5553RTTQIOOUTKQNUTOZW
    Forms.Settings_Filters: 3QH7PPZFG5CAVB644Y7ZXCULXPX4GE6G
    Forms.Settings_User.SignUp: ROSZ53MVKTFA5CNBXTGQPTDGWQTP24A4
    Forms.Work_Viewer: MOSG7GFC3LYEBTE5CIQ7DNXXEMJVHA6M
    Forms.Editor_NewWork: UGRZC7337FUPXH3ENG5VKXNYBI52E6Z6
    Forms: MQBVKOY5CR22YKZEGAITKBEQLXRSS4BF
    Forms.Settings_Interface: 7AH4UX4YJI6JBZERYX7ZWRWKEZ2HQEMV
    Forms.Reader_Today: WBZRH2LF3OAARKNKW25OIKITBUAEND2Z
    Forms.Settings_User: NDG3NXNMZXMJQ2DJND5DECALZTWGUISA
    Data: ABUP2I6ZF7QDBSCD55WFU4HV6CB2HU6D
    Forms.Settings_Info: AJQDZ3HVM6R7PSQFABRNDAJWX5PIEPPA
    Index.Main: V56GQWUZZ35R7VYKQYSH37DKHQF2ZBMJ
    Data.ChartsData: VHVWEQUBTYNUCKIT7RW2TE3XK7O573T5
    Forms.Reader_Authors: I3BDZUQW6GAESWS24LZWKX527JPSC6Z3
    Forms.Settings_User.LogOut: '1717357959667158387906752.60196'
    Forms.Reader_Settings: MKXVAQSYCQK5RROEX62FH3UHSCY2FZIQ
    Forms._FormBlank: UOJGQMM7YNRA7GI34JGMUOMU7WHNAG4X
    Database: EONA6XDY6XQXJQTQBDX3D7VTS6BYOFKK
    Forms.Author_Works: VULYXG57WBKTMFFCJ3YM3AIFKAAYZQGV
  server_modules:
    Devices: DM7K3UYVCI743REYTT2EGFIS6NBCM6B5
    IDGenerator: RDMAF642AEUMAKKKF6CDBUPJ43ZL7AUO
    Users: LPXXLMC7MDU2TC47SW2ECZKFH2FT4DQQ
  assets:
    html/reader_works.html: 3KTG54E452EZX5P3I7GACYXLD6C2TRD6
    javascript/lokijs.js: '1714559465754781553759674.2985'
    javascript/init_viewport.js: 6MFUH7IYQ6RWSKDMGSMTVE53V3VH5FMP
    javascript/cheteme_api.js: VFQ572EUOGSH4Y7FGJTKH2GGME3RNVTL
    theme.css: OM4QHS3T52XAMHYZPR3CEKGZTODZKSWD
    javascript/init.js: J7CROCZFMCEO6IZYIK6GEWYOMURF4K2Q
    html/author_new.html: '1715166413632712935909092.6045'
    html/index_form.html: 3CGIJ6DL5PKUAEZ4ZEFE2BARKZP3APQB
    javascript/load_loki.js: '1714653748396677993731114.6569'
    html/author_editor.html: CMHCUJNPCWN24KPA3LHHQBYUYYN2N76B
    javascript/.gitkeep: '1715166528253847833721460.5741'
    standard-page.html: KPUFTZL5E4GRYMCVZOZK2W44M2T2ABTQ
    javascript/coll_loki.js: 3PP334TDQEKEVEOSID6XSRMSZJJB3GHY
    html/reader_today.html: TISI6XTRKM76Z6IDRPTZMWEG7SI3ISBT
    javascript/init_clicks.js: 7FYPFEGMNLHA5NJ2I4Q64V7O4YNUCZFG
    html/author_publish.html: EXQHZCWTJ6B3IBCWMOAZH32RYCRHTS4F
    javascript/load_quill.js: RXQLMPD3U2E2YM3GY3FVDJQR6PU64HAF
    javascript/quill_counter.js: YLZGCIOGTXVZMGIBRZVKZZBWJG64PZ7J
    html/reading_read.html: 4YLVHYEMP42HHO5YAVZD2KPHX2BK3ZZ7
    chetemecover.webp: '1714479494193739084299907.0813'
    html/reader_authors.html: Q2OA6U3NEYSLLHNQON7FOZE4Y3P3FMDD
    javascript/loki-indexed-adapter.js: '1714563761236511864562359.80615'
    html/form.html: ENSTM6XOQV63QGZ2ZH6SP3QWT26S6T63
    html/.gitkeep: '1715166384597191934429518.11136'
  scripts: {}
