unique_ids:
  forms:
    Forms._FormTemplate: CR555ETJYVC7OP4KRQZXPBG6WJOFRZ33
  modules:
    Forms.ViewerW_Cover: PMDPPUUIKXEHLL6AAQJP4GRIVTGGATMC
    API.ReaderApi: I7JEN5JG3CJNBF3JEJKFBQPELRW7F46L
    Forms.Editor_Publish: JHL4YIMINUWDZEXRAFJ767JFDTRBGJXH
    Forms.Editor_Cover.ImageCover: VR3YIKPFPNDCLN6URCUAOIES7H4E5EL3
    Index: BLGAWSOBHTMN7ULTMMSJB347KCDBGAFZ
    Forms.Author_Stats: UEWT6U25NYJGEQXJ56ILSNVFD2IHBSU3
    Index.App: CI6THZVGTL4BDFHIOLWXA5ZKBEOOQVOV
    Forms.ViewerW_Work: GUGSAV6NITHYDTQSYPJOXWA4CFJ6F7NN
    Forms.Reader_Charts: VLSSXS25OQKWJS6A2PCAVTXUOKKSR45O
    Forms.Editor_Tags.GuessGenres: ICM6IEL4WD3N3L4KRZI7CLSNAJRR2TTS
    PyScript: LFUVTXV2M5TRDYL6C7M5BJTVLWXDRM6U
    Forms.Reader_Bookmarks: KDK6I6PZMEMQFNRKF4MN66GFQCOASVBP
    Forms._Welcome: VC5L7UHUKZP5H7GLWQ2GYGGDX6WUMWIP
    Index.DevMode: ZXV5QFEPGF3DR5LG23BJIIGZJNSNVJJH
    Index.Device: G5H2CSQW7N2DWVGH2H7NTYRQLTFDOAPU
    Navigation.NavigationBar: 2VMZNWBGM5EXM3ABSMBCAHJULBYF7DZ6
    Navigation: 4REX5LJ6FFN6S6XJZFW5NV5KZATKOFO3
    Database.ChartsDB: OQXMDFVWRIYXNAMUIEZUZNMPKEUAYQJE
    Forms.Settings_User.ZodParse: TXEWPWHTGESAZ2F7V5NM5AX6OG7ABADP
    Forms.ViewerA_Works: F7MRTFM6YZ5NGVNC6MITBLGJHK24CW7R
    Index.AuthorMode: MRMC5FLGZJ6SLNQ6VCWPBPTKJH56T2VO
    API: CP56YHYAHSBKWNSNMHFS5A7IYXXJXOI6
    Database.AwesomeDB: 3N4QVH6DW6OCUDZG5B2M67T4GLVW6ABE
    Forms.Author_Profile: TK4ACO5DVWOAX5OAYHLPR7VLR6H3FEKH
    Forms.Editor_Cover.Contrast: JXFW53WBUQSVAURMABIHGDMCAZFYU3CW
    Database.EngageDB: W5GJWPTWXIUW2BGMA4SF2N3OCADBZU4F
    PyScript.PyScriptLoader: 4QVBLP3Z74DPEJKKKIOSIXPB7FL5F3ON
    Forms.Editor_Cover: J5HX3NEBVP4AUJLJNLIRSFAD7MQLBAW3
    Database.ReaderDB: TKICPFHI3B5FSVWIKFVRMJ4K43ZX43BF
    Forms.Settings_User.Login: E6N6MYGAN5N5553RTTQIOOUTKQNUTOZW
    Forms.Settings_Filters: 3QH7PPZFG5CAVB644Y7ZXCULXPX4GE6G
    Forms.Author_Profile.Zod_Parse: 5WGONAFTM6NWBJ6TFAMAAXMJPKWQP7SE
    Forms.ViewerA_Author: V4AUYA5LJDAKFC6XPFPCUVWENORSB3JI
    Forms.Settings_User.SignUp: ROSZ53MVKTFA5CNBXTGQPTDGWQTP24A4
    Database.EditorDB: RUYXGNHBCSOBR2ARU7HCA2MZGFNHHNTO
    Forms.Author_PWorks: 6I64LNGINR3F7HAY4QNYGFS3WEGFCXNN
    API.ImagesApi: ITX5OQHXZM3QCNCYG3MDVNN34PZRT2V5
    Forms.Editor_Work: NTYIPY7WJOX6UJ63CZU75JEW4PWL3MHF
    Forms.Editor_Cover.Fonts: GQLT4CVONHN364OXHRCPPN6ACRCZ5V5T
    API.DeviceIDApi: 7IBRJV6NBERPYEB5QRV7XJKVJGSKZKR3
    Forms: MQBVKOY5CR22YKZEGAITKBEQLXRSS4BF
    API.EngagementApi: 4NV7C6FXZ3YBMTY4M5FKRKX5VYTWI4KJ
    API.ChartsApi: TU6MZOIBD3CRKM2HTJTBFAUWKHC4FBF4
    Helpers: UAZEUJS3C643I6ESP5TLBUVFVQVOUXBU
    Forms.Author_NewWork.WorkTemplate: WB5KV3KQSPAYMN67JMWPWLGLIJSTYMPN
    Forms.Editor_Tags: VUDYCF6WDOUW7SB4VQQ3A4A5Z7W5K2XA
    Forms.Settings_Interface: 7AH4UX4YJI6JBZERYX7ZWRWKEZ2HQEMV
    Forms.Editor_Cover.CoverElement: Y3BQE4736WZL5ERSVSI3QDZAHV5HYORR
    Forms.Reader_Today: WBZRH2LF3OAARKNKW25OIKITBUAEND2Z
    Forms.Settings_User: NDG3NXNMZXMJQ2DJND5DECALZTWGUISA
    Forms.ViewerW_Engage: BU6P37XGXFJMDFQK4P2KHOMXWS6ZNIGT
    Data: ABUP2I6ZF7QDBSCD55WFU4HV6CB2HU6D
    Forms.Settings_Info: AJQDZ3HVM6R7PSQFABRNDAJWX5PIEPPA
    Index.Main: V56GQWUZZ35R7VYKQYSH37DKHQF2ZBMJ
    Data.ChartsData: VHVWEQUBTYNUCKIT7RW2TE3XK7O573T5
    Forms.Author_NewWork: BYTB6NF7HBP2TB4YSDSUNIWVU77DTSWB
    Forms.Reader_Authors: I3BDZUQW6GAESWS24LZWKX527JPSC6Z3
    Forms.Settings_User.LogOut: '1717357959667158387906752.60196'
    Database.GenresDB: 3YQPDTOFLKDWT6BAZ3IZPR4QDNZEJIXV
    Forms.Reader_Settings: MKXVAQSYCQK5RROEX62FH3UHSCY2FZIQ
    Database.GenresData: KA5KFHFSE4N52IHPCNYH3XUJGHMMS4ZJ
    Forms._FormBlank: UOJGQMM7YNRA7GI34JGMUOMU7WHNAG4X
    Database: EONA6XDY6XQXJQTQBDX3D7VTS6BYOFKK
    Forms.Editor_Cover.URI_parser: KIXLWPCCLWZOMHPDCKWCW5LDR7UUEJXO
    Forms.Author_Works: VULYXG57WBKTMFFCJ3YM3AIFKAAYZQGV
  server_modules:
    AuthorProfiles: H6MNWAUAJARAUAY5FRFJLLXOPI4ZNKJ6
    IDGenerator: RDMAF642AEUMAKKKF6CDBUPJ43ZL7AUO
    Suspicious: XZ7VLLWURKXCXFASFFWRHTOZ7Y6MSP7L
    Helpers: HYGIXN6ETKGHTRQELV5G5WQWCCXE3HLT
    CloudflareAuthors: Z7Z3BYJCVSW7G554CDSF5W3ROPAZGSCQ
    Users: LPXXLMC7MDU2TC47SW2ECZKFH2FT4DQQ
    AuthorPublishWork: 7CAS7JL4ACOBVCYP4AAWXLIOG5FYDOKU
    Devices: DM7K3UYVCI743REYTT2EGFIS6NBCM6B5
    Registry: C56N6TF3G54KVZ6O3MBQSJX5UVAOOVTJ
  assets:
    pyscript/PDF_parser.py: XLTVO72WAF2CEAOHQFM2DOIIVTZ3P4NP
    pyscript/MD_parser.toml: JGYP5XE2LVON4CEHUESXWIHLGBOC36ND
    html/reader_works.html: 3KTG54E452EZX5P3I7GACYXLD6C2TRD6
    javascript/lokijs.js: '1714559465754781553759674.2985'
    javascript/init_viewport.js: 6MFUH7IYQ6RWSKDMGSMTVE53V3VH5FMP
    pyscript/new_work.toml: XWYLXAABF5VNDNCLMDX652VQHX5I55EM
    javascript/cheteme_api.js: VFQ572EUOGSH4Y7FGJTKH2GGME3RNVTL
    theme.css: OM4QHS3T52XAMHYZPR3CEKGZTODZKSWD
    pyscript/main.py: AV4LNTBN7EI6GW32GWVIGQCCP2VK6MNL
    javascript/init.js: J7CROCZFMCEO6IZYIK6GEWYOMURF4K2Q
    html/author_new.html: '1715166413632712935909092.6045'
    html/index_form.html: 3CGIJ6DL5PKUAEZ4ZEFE2BARKZP3APQB
    javascript/load_loki.js: '1714653748396677993731114.6569'
    fonts/ADYS.ttf: NHLXZLQGC4GYMJQUAYECWLIGPG2JFJ4Z
    html/author_editor.html: CMHCUJNPCWN24KPA3LHHQBYUYYN2N76B
    javascript/.gitkeep: '1715166528253847833721460.5741'
    standard-page.html: KPUFTZL5E4GRYMCVZOZK2W44M2T2ABTQ
    javascript/coll_loki.js: 3PP334TDQEKEVEOSID6XSRMSZJJB3GHY
    html/reader_today.html: TISI6XTRKM76Z6IDRPTZMWEG7SI3ISBT
    pyscript/new_work.py: IXJI5PCDQUMGROE7J46RT3ZJP4JELZDC
    javascript/init_clicks.js: 7FYPFEGMNLHA5NJ2I4Q64V7O4YNUCZFG
    html/author_publish.html: EXQHZCWTJ6B3IBCWMOAZH32RYCRHTS4F
    javascript/load_quill.js: RXQLMPD3U2E2YM3GY3FVDJQR6PU64HAF
    javascript/quill_counter.js: YLZGCIOGTXVZMGIBRZVKZZBWJG64PZ7J
    html/reading_read.html: 4YLVHYEMP42HHO5YAVZD2KPHX2BK3ZZ7
    chetemecover.webp: '1714479494193739084299907.0813'
    html/reader_authors.html: Q2OA6U3NEYSLLHNQON7FOZE4Y3P3FMDD
    javascript/loki-indexed-adapter.js: '1714563761236511864562359.80615'
    html/form.html: ENSTM6XOQV63QGZ2ZH6SP3QWT26S6T63
    pyscript/DOCX_parser.toml: ASAOPKYNH3JNFM2U3KVZIRWRXENTXCEA
    pyscript/MD_parser.py: EP5KEET4K35FSFKNCWA2CB7342DC3BJ2
    pyscript/DOCX_parser.py: ADT6VVWJZ6LKE6QETIBYICVXVGBSIIOM
    html/.gitkeep: '1715166384597191934429518.11136'
    pyscript/PDF_parser.toml: R6N6QB5FOA7M5RFR7G7I7XEFYHCWD7VU
    pyscript/main_settings.toml: KXQ3QRII5FF6KTPW6HIQZTKNKMB7ASHX
    pyscript/md_parser.html: KSBRVMPYHV5FRCJYCY4PZEXYIJTKAZXT
  scripts: {}
