keywords = [
#menus
    {'bg':'днес', 'name':'home'},
    {'bg':'автори', 'name':'glasses'},
    {'bg':'творби', 'name':'books'},
    {'bg':'отметки', 'name':'bookmark'},
    {'bg':'вход', 'name':'user'},
    {'bg':'настройки', 'name':'sliders'},
    {'bg':'автор', 'name':'typewriter'},
    {'bg':'създай', 'name':'file-plus'},
    {'bg':'стат', 'name':'chart-simple'},
    {'bg':'профил', 'name':'address-card'},
    {'bg':'тест', 'name':'icons'},

#genres
    {'bg':'поезия', 'name':'align-center'},
    {'bg':'проза', 'name':'align-left'},
    {'bg':'микро разказ','name':'t'}, #up to 100 words
    {'bg':'флашфикшън','name':'s'}, #100 to 1,000 words
    {'bg':'разказ','name':'m'}, #1,000 to 7,500 words
    {'bg':'повест','name':'l'}, #7,500 то 17,500words
    {'bg':'новела','name':'x'}, #17,500 to 40,000 words
    {'bg':'роман','name':'h'}, #40к - 100к

    {'bg':'стих', 'name':'s'},
    {'bg':'хайку', 'name':'t'},
    {'bg':'стихотворение', 'name':'m'},
    {'bg':'епос', 'name':'l'},

  
    {'bg':'фентъзи', 'name':'hat-wizard'},
    {'bg':'фантастика', 'name':'starship'},
    {'bg':'ужаси', 'name':'face-scream'},
    {'bg':'драма', 'name':'masks-theater'},
    {'bg':'трилър', 'name':'gun'},
    {'bg':'крими', 'name':'handcuffs'},
    {'bg':'исторически', 'name':'fort'},
    {'bg':'романс', 'name':'shield-heart'},
    {'bg':'детски', 'name':'teddy-bear'},
    {'bg':'съвременни', 'name':'calendar-star'},
    {'bg':'хумор', 'name':'face-grin-squint-tears'},
    {'bg':'приключенски', 'name':'map-location'},
    {'bg':'действителни', 'name':'badge-check'},
    {'bg':'еротика', 'name':'venus-mars'},
#subgenres
    {'bg':'научна', 'name':'atom'},
    {'bg':'класическа', 'name':'robot'},
    {'bg':'киберпънк', 'name':'space-station-moon-construction'},
    {'bg':'соларпънк', 'name':'trillium'},
    {'bg':'стиймпънк', 'name':'steam-symbol'},
    {'bg':'утопия', 'name':'omega'},
    {'bg':'антиутопия', 'name':'user-bounty-hunter'},
    {'bg':'постапокалипсис', 'name':'house-chimney-crack'},
    {'bg':'биопънк', 'name':'vial-virus'},
    {'bg':'технотрилър', 'name':'raygun'},
    {'bg':'шпионска', 'name':'radar'},
    {'bg':'хумористична', 'name':''},
    {'bg':'супергерои', 'name':'mask'},
    {'bg':'военна', 'name':'jet-fighter-up'},
    {'bg':'детективски', 'name':'user-secret'},
    {'bg':'психопати и серийни убийци', 'name':'hockey-mask'},
    {'bg':'мистерии', 'name':'block-question'},
    {'bg':'техно', 'name':'microchip'},
    {'bg':'психологически', 'name':'brain'},
    {'bg':'шпионски', 'name':'syringe'},
    {'bg':'политически', 'name':'scale-unbalanced'},
    {'bg':'романтичен', 'name':'heart-pulse'},
    {'bg':'експериментална', 'name':'head-sgide-brain'},
    {'bg':'поток на мисълта', 'name':'brain-arrow-curved-right'},
    {'bg':'епистоларна', 'name':'minimize'},
    {'bg':'мемоари', 'name':'book-font'},
    {'bg':'лгтб+', 'name':'transgender'},
    {'bg':'пътепис', 'name':'globe-stand'},
    {'bg':'гурме', 'name':'pot-food'},
    {'bg':'чиклит', 'name':'candy'},
    {'bg':'феминизъм', 'name':'venus'},
    {'bg':'историческа', 'name':'crown'},
    #{'bg':'военна', 'name':'person-military-to-person'},
    {'bg':'любовна', 'name':'heart-crack'},
    {'bg':'семейна сага', 'name':'family'},
    {'bg':'политическа', 'name':'podium-star'},
    {'bg':'по действителни събития', 'name':'monument'},
    {'bg':'историческа фикция', 'name':'angel'},
    {'bg':'исторически трилър', 'name':'chess'}
]